server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/x-cargo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xcargo_Diego

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false

  hibernate:
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl